Repository SOPT-all/36-COLLABORATION-ANDROID-HOLIX, pull requests merged in 2025-05, with the labels that each got.

#16 [feature/#7] 내 클럽 뷰컴포넌트
  app/src/main/java/org/sopt/holix/core/type/MyClubStatus.kt
  app/src/main/java/org/sopt/holix/core/type/MyClubTab.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/MyClubRoute.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/component/MyClubCard.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/component/MyClubPinButton.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/component/MyClubRecommendCard.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/component/MyClubStatusChip.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/component/MyClubTabRow.kt
  app/src/main/res/values/strings.xml
Labels: 예인, feature

#19 [feature/#18] 내 클럽 뷰 화면
  app/src/main/java/org/sopt/holix/domain/model/MyClubEntity.kt
  app/src/main/java/org/sopt/holix/domain/model/RecommendClubEntity.kt
  app/src/main/java/org/sopt/holix/presentation/main/HolixNavHost.kt
  app/src/main/java/org/sopt/holix/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/holix/presentation/main/MainNavigator.kt
  app/src/main/java/org/sopt/holix/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/MyClubNavigation.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/MyClubRoute.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/MyClubSideEffect.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/MyClubState.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/MyClubViewModel.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/component/MyClubTabRow.kt
  app/src/main/res/values/strings.xml
Labels: 예인, feature

#21 [setting/#20] 서버 기초 세팅
  app/src/main/java/org/sopt/holix/data/datasource/ClubDataSource.kt
  app/src/main/java/org/sopt/holix/data/datasource/MainDataSource.kt
  app/src/main/java/org/sopt/holix/data/di/RepositoryModule.kt
  app/src/main/java/org/sopt/holix/data/di/ServiceModule.kt
  app/src/main/java/org/sopt/holix/data/dto/response/BaseResponse.kt
  app/src/main/java/org/sopt/holix/data/repository/ClubRepositoryImpl.kt
  app/src/main/java/org/sopt/holix/data/repository/MainRepositoryImpl.kt
  app/src/main/java/org/sopt/holix/data/service/ClubService.kt
  app/src/main/java/org/sopt/holix/data/service/MainService.kt
  app/src/main/java/org/sopt/holix/domain/repository/ClubRepository.kt
  app/src/main/java/org/sopt/holix/domain/repository/MainRepository.kt
Labels: 예인, feature

#15 [feature/#5] 클럽상세 뷰 구현
  app/build.gradle.kts
  app/src/main/java/org/sopt/holix/presentation/club_detail_home/ClubDetailHomeItem.kt
  app/src/main/java/org/sopt/holix/presentation/club_detail_home/ClubDetailHomeNavigation.kt
  app/src/main/java/org/sopt/holix/presentation/club_detail_home/ClubDetailHomeRoute.kt
  app/src/main/java/org/sopt/holix/presentation/club_detail_home/ClubDetailHomeSideEffect.kt
  app/src/main/java/org/sopt/holix/presentation/club_detail_home/ClubDetailHomeState.kt
  app/src/main/java/org/sopt/holix/presentation/club_detail_home/ClubDetailHomeViewModel.kt
  app/src/main/res/drawable/img_club_main_and.png
  app/src/main/res/drawable/speech_bubble_and.xml
  gradle/libs.versions.toml
Labels: feature

#22 feature/#5: ClubMenuItem 분리 후 entries 적용, contentDescprition 하드코딩 대신 stringResource 적용
  app/src/main/java/org/sopt/holix/presentation/club_detail_home/ClubDetailHomeRoute.kt
  app/src/main/java/org/sopt/holix/presentation/club_detail_home/ClubMenuItem.kt
  app/src/main/res/values/strings.xml
Labels: 지우, feature, refactor

#13 [feature/#9] 클럽 디테일 채팅 햄버거 메뉴 컴포넌트, 뷰 구현
  app/src/main/java/org/sopt/holix/core/designsystem/component/StableImage.kt
  app/src/main/java/org/sopt/holix/data/datasource/ChattingDataSource.kt
  app/src/main/java/org/sopt/holix/data/di/ServiceModule.kt
  app/src/main/java/org/sopt/holix/data/dto/response/chatting/ChattingBaseResponse.kt
  app/src/main/java/org/sopt/holix/data/dto/response/chatting/ChattingResponseDto.kt
  app/src/main/java/org/sopt/holix/data/repository/chatting/ChattingRepositoryImpl.kt
  app/src/main/java/org/sopt/holix/data/service/ChattingService.kt
  app/src/main/java/org/sopt/holix/domain/model/chatting/ChattingListDataEntity.kt
  app/src/main/java/org/sopt/holix/domain/model/chatting/ChattingScreenType.kt
  app/src/main/java/org/sopt/holix/domain/model/chatting/ChattingType.kt
  app/src/main/java/org/sopt/holix/domain/repository/ChattingRepository.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingHamburgerRoute.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingRoute.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingSideEffect.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingState.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingViewModel.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingItem.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingItemBubbleAndBottom.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingItemTop.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingMyBubbleAndChip.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingSystemMessage.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingTextField.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/hamburger/ChattingClubExit.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/hamburger/ChattingHamburgerMemberItem.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/hamburger/ChattingHamburgerMemberLazyColumn.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/hamburger/ChattingHamburgerMemberProfile.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/hamburger/ChattingHamburgerMenu.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/hamburger/ChattingHamburgerPhotoLazyRow.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/hamburger/ChattingHamburgerTopBar.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/core/ChattingTopBar.kt
  app/src/main/res/drawable/ic_add_circle_blue.xml
  app/src/main/res/drawable/ic_like_circle_blue.xml
  app/src/main/res/drawable/img_chat_photo_1.png
  app/src/main/res/drawable/img_chat_photo_2.png
  app/src/main/res/drawable/img_chat_photo_3.png
  app/src/main/res/drawable/img_chat_photo_4.png
  app/src/main/res/values/strings.xml
Labels: 민성, feature

#17 [feature/#6] 홈화면 뷰 컴포넌트
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/holix/data/dto/response/DummyResponseDto.kt
  app/src/main/java/org/sopt/holix/data/dto/response/StudyReponseDto.kt
  app/src/main/java/org/sopt/holix/domain/model/Study.kt
  app/src/main/java/org/sopt/holix/presentation/home/HomeScreen.kt
  app/src/main/java/org/sopt/holix/presentation/home/HomeState.kt
  app/src/main/java/org/sopt/holix/presentation/home/HomeViewModel.kt
  app/src/main/java/org/sopt/holix/presentation/home/component/BannerCarousel.kt
  app/src/main/java/org/sopt/holix/presentation/home/component/CategoryChips.kt
  app/src/main/java/org/sopt/holix/presentation/home/component/CourseSection.kt
  app/src/main/java/org/sopt/holix/presentation/home/component/SearchTopBar.kt
  app/src/main/java/org/sopt/holix/presentation/home/component/TabRowSection.kt
  app/src/main/java/org/sopt/holix/presentation/home/component/TagChip.kt
  app/src/main/java/org/sopt/holix/presentation/home/dummyData/DummyStudyData.kt
  app/src/main/java/org/sopt/holix/presentation/home/model/Category.kt
  app/src/main/java/org/sopt/holix/presentation/home/model/StudyUiModel.kt
  app/src/main/java/org/sopt/holix/presentation/home/model/TabList.kt
  app/src/main/java/org/sopt/holix/presentation/home/model/Thumbnail.kt
  app/src/main/java/org/sopt/holix/presentation/mapper/StudyUiMapper.kt
  app/src/main/res/drawable/ic_career.png
  app/src/main/res/drawable/ic_heart.png
  app/src/main/res/drawable/ic_studying.png
  app/src/main/res/drawable/ic_tech.png
  app/src/main/res/values/strings.xml
Labels: feature

#30 [feature/#25] 나의 클럽 api 연결
  app/src/main/java/org/sopt/holix/data/datasource/ClubDataSource.kt
  app/src/main/java/org/sopt/holix/data/di/RepositoryModule.kt
  app/src/main/java/org/sopt/holix/data/di/ServiceModule.kt
  app/src/main/java/org/sopt/holix/data/dto/response/myclub/MyClubResponseDto.kt
  app/src/main/java/org/sopt/holix/data/repository/ClubRepositoryImpl.kt
  app/src/main/java/org/sopt/holix/data/service/ClubService.kt
  app/src/main/java/org/sopt/holix/domain/repository/ClubRepository.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/MyClubRoute.kt
  app/src/main/java/org/sopt/holix/presentation/myclub/MyClubViewModel.kt
  gradle/libs.versions.toml
Labels: 예인, feature

#29 [feature/#27] 클럽 채팅 navigation
  app/src/main/java/org/sopt/holix/core/navigation/Route.kt
  app/src/main/java/org/sopt/holix/data/datasource/ChattingDataSource.kt
  app/src/main/java/org/sopt/holix/data/datasource/ClubDataSource.kt
  app/src/main/java/org/sopt/holix/data/di/ServiceModule.kt
  app/src/main/java/org/sopt/holix/data/dto/request/ChattingRequestDto.kt
  app/src/main/java/org/sopt/holix/data/dto/response/chatting/ChattingPostResponseDto.kt
  app/src/main/java/org/sopt/holix/data/dto/response/chatting/ChattingResponseDto.kt
  app/src/main/java/org/sopt/holix/data/repository/ClubRepositoryImpl.kt
  app/src/main/java/org/sopt/holix/data/repository/chatting/ChattingRepositoryImpl.kt
  app/src/main/java/org/sopt/holix/data/service/ChattingService.kt
  app/src/main/java/org/sopt/holix/data/service/ClubService.kt
  app/src/main/java/org/sopt/holix/domain/model/chatting/ChattingDataEntity.kt
  app/src/main/java/org/sopt/holix/domain/model/chatting/ChattingListDataEntity.kt
  app/src/main/java/org/sopt/holix/domain/model/chatting/ChattingScreenType.kt
  app/src/main/java/org/sopt/holix/domain/repository/ChattingRepository.kt
  app/src/main/java/org/sopt/holix/domain/repository/ClubRepository.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingHamburgerRoute.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingRoute.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingState.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/ChattingViewModel.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingItemBubbleAndBottom.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingMyBubbleAndChip.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingTextField.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/ChattingTopBar.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/components/detail/hamburger/ChattingHamburgerTopBar.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/core/ChattingTopBar.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/navigation/ChattingDetailHamburgerNavigation.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/navigation/ChattingNavigation.kt
  app/src/main/java/org/sopt/holix/presentation/chatting/utils/DataUtils.kt
  app/src/main/java/org/sopt/holix/presentation/main/HolixNavHost.kt
  app/src/main/java/org/sopt/holix/presentation/main/MainNavigator.kt
Labels: 민성, feature, refactor
